name: 'vertigo_analytics'
version: '1.0.0'
config-version: 2


profile: 'vertigo_db'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

models:
  vertigo_analytics:
    materialized: table  