vertigo_db:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost      
      user: vertigo        # according to docker-compose.yml env_file
      password: '123456'   # same 
      port: 5432
      dbname: vertigo_db
      schema: public
      threads: 1